package in.co.Exceptionhandlng;

public class Testarithmetic {
	public static void main(String[] args) {
		 int i = 0;
		 int k = 15;
		
		try { 
			//double divl = i/k;
			//System.out.println("div is"+div);
			
		}catch (Exception e) {
		System.out.println(e.getMessage());
		//e.printStackTrack()
		}finally {
			System.err.println("0 is not divisible by 15");}
		System.out.println("hello ram");
		}
		
	}


